{% set name = "make-it-sync" %}
{% set version = "2.1.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/make_it_sync-{{ version }}.tar.gz
  sha256: 47fe27b34537f9e3b09a869b6e0e7c723026cfc3e12087d8e248bf55506ced28

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - make_it_sync
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gordonwatts/make-it-sync
  summary: Create a sync version of an async function
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gordonwatts
    - matthewfeickert
